// react-app/react-app-vite/src/components/error/404.tsx
/**
 * @Author: forguo
 * @Date: 2022/6/12 17:54
 * @Description: 404
 */
import {Link} from "react-router-dom";
import {Button, Result} from "antd";
import React from "react";

export default () => {
    return (
        <Result
            status="404"
            title="404"
            subTitle="Sorry, the page you visited does not exist."
            extra={<Link to='/'>
                <Button type='primary'>返回首页</Button>
            </Link>}
        />
    )
}

// vue-app/vue2-app/src/views/Error/404/index.vue
<template>
    <div>
        <el-result icon="info" title="404" subTitle="Page Not Found">
            <template slot="extra">
                <el-link type="primary" size="medium" href="/">返回首页</el-link>
            </template>
        </el-result>
    </div>
</template>
<script>
export default {
    name: 'Error404'
}
</script>
